# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemona', '0008_auto_20160324_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modem',
            old_name='imsi_sim',
            new_name='imsi',
        ),
        migrations.RenameField(
            model_name='probe',
            old_name='mac_address',
            new_name='baseboard_mac',
        ),
        migrations.RenameField(
            model_name='probe',
            old_name='control_sw_version',
            new_name='csw_version',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='apn',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='apn_password',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='apn_user',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='ethernet_test_status',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='fw',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='ras',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='test_status',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='wifi_test_status',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='communication_device',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='critical_sd_size',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='dns',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ethernet_status',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ethernet_test_status',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ftp_address',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ftp_login',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ftp_mode',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ftp_password',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ftp_period',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ftp_port',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='gps_status',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='http_address',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='http_period',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='http_port',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ip_gateway',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ip_mask',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='memory_size',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='position_system',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='probe_status',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='ssid',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='wifi_encription',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='wifi_password',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='wifi_security',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='wifi_state',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='wifi_status',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='wifi_test_status',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='work_mode',
        ),
        migrations.AddField(
            model_name='modem',
            name='name',
            field=models.CharField(max_length=16, null=True, blank=True, verbose_name='Modem name'),
        ),
        migrations.AddField(
            model_name='probe',
            name='ram_size',
            field=models.IntegerField(default=0, verbose_name='Memory Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probe',
            name='sn',
            field=models.CharField(max_length=50, default=0, unique=True, verbose_name='Serial number'),
            preserve_default=False,
        ),
    ]
